### ISSUE TITLE
More Features with Project Evoli

### ISSUE THREAD

**Issue by LopeKinz** [Rud3p/Infrarat#1]
Project Evoli is a Python "Extention" To easily create or upgrade Rats. It has a ton of features that can be copied and added into your own rat. (But you need to give credits) 

WARNING : Project Evoli has as alot of desturctive Features!

https://github.com/LopeKinz/project-evoli

**Comment by LopeKinz** [comment]
If you need anything add me on discord : legendpinkyhax

**Comment by Rud3p** [comment]
okay, thanks for the tip
